
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
os:
  - linux
  # - osx # TravisCI doens't support Python :( https://github.com/travis-ci/travis-ci/issues/9744
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # - libc++-dev
    - gcc-7
    - g++-7
    - libsuitesparse-dev
env:
  - CC=gcc-7 && CXX=g++-7 && PCU_DEBUG=true
  # - CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++"
install:
  - pip install .
script:
  - cd tests
  - python -m unittest --verbose
