site_name: Point Cloud Utils
nav:
  - Home: index.md
#  - About: about.md
  - Functionality:
      - "Mesh I/O": sections/mesh_io.md
      - "Point Cloud Resampling": sections/point_cloud_resampling.md
      - "Mesh Sampling": sections/mesh_sampling.md
      - "Shape Metrics": sections/shape_metrics.md
      - "Mesh Signed Distances": sections/mesh_sdf.md
      - "Normal Estimation": sections/normal_estimation.md
      - "Ray/Mesh Intersection": sections/ray_mesh_intersection.md
      - "Mesh Smoothing": sections/mesh_smoothing.md
theme:
  name: readthedocs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
